### ISSUE TITLE
[6/30(목)] 코루틴

### ISSUE THREAD

**Issue by onisley** [CodingBakery/KotlinStudy#11]
### 개요
- 코루틴의 기초에 대해서 학습한다.
- 심도있는 상세 내용들은 다루지 않고 Hello, World 수준으로 진행한다.
- 문서: https://github.com/CodingBakery/KotlinStudy/blob/main/content/%EC%BD%94%EB%A3%A8%ED%8B%B4_%EA%B8%B0%EC%B4%88.md

**Comment by DevBono** [comment]
### 필수는 아니지만 충분히 좋은 도구 

Kafka 와 같은 메시지 플랫폼을 이용한 이벤트 드리븐 방식의 설계나, 단순히 쓰레드만을 이용하여도 충분한 퍼포먼스를 낼 수는 있다. 
하지만 쓰레드가 블록되는 시간까지 알차게 사용이 가능해진다는 점에서 효율이 좋다고 생각됨  
대량의 데이터를 빠르게 처리해야하는 경우는 고려해볼만 함 
안드로이드 같은 경우 코딩 패러다임의 변화 가능 (순차적 코드처럼 짜는 콜백 함수) 

스코프와 컨텍스트에 대한 이해를 하면 더 심도있는 개념 파악이 가능해질 듯
