### ISSUE TITLE
[7/7(목)] 생성자

### ISSUE THREAD

**Issue by eyeeshot** [CodingBakery/KotlinStudy#13]
### 개요
- 기본생성자, 생성자 속성 정의하기.

**Comment by onisley** [comment]
발표자료: <a href="https://github.com/CodingBakery/KotlinStudy/blob/main/content/%EC%BD%94%ED%8B%80%EB%A6%B0_%EC%83%9D%EC%84%B1%EC%9E%90.md">코틀린 생성자</a>
