### ISSUE TITLE
[6/9(목)]코틀린에서 함수형 프로그래밍 하기

### ISSUE THREAD

**Issue by onisley** [CodingBakery/KotlinStudy#2]
- 진행 날짜: 6/9(목)

**Comment by onisley** [comment]
# 이야기들
> 6월 9일 13:00 - 14:00 스터디 발표 때 등장했던 주제들을 요약했습니다.

### 코드 가독성
 - 고차함수 체이닝이 조금만 많아져도 로직 파악이 어려움.
 - 함수 구현체가 복잡해지면 가독성이 매우 떨어짐.
 - 요구사항이 변경되었을 때 기존 로직에 추가하기 힘든 케이스가 발생할 수 있음.
 - 이렇게 하면 어떨까요?
    - 가독성을 고려한 네이밍
    - 함수로 작성하는 코드는 가볍게 단위 기능 위주로 작성

### 일급객체와 고차 함수
 - 일급객체: 
    - 변수에 할당할 수 있고
    - 다른 함수의 인자로 전달할 수 있으며
    - 다른 함수의 결과로도 반환될 수 있는 것!
 - 고차함수: 다른 함수를 인자로 받거나, 리턴하는 함수

### 함수 내부의 함수를 바깥 함수에서 접근 (ex. JS의 클로저 함수)
- 자바는 final인 것만 사용 가능하게 컴파일을 막아두는데
- 코틀린은 수정도 가능? 왜 그럴까요?

### 또 다른 고민들
- 순수 함수의 디버깅을 어떻게 할 수 있을까에 대한 고민
- 어떤 것을 함수로 만들지, 어떤 것을 클래스로 만들지에 대한 고민

**Comment by eager20** [comment]
### 함수형 프로그래밍에 대한 평가.

> 잠시 당신이 나무꾼이라고 가정해보자. 당신은 숲에서 가장 좋은 도끼를 가지고 있고, 그래서 가장 일 잘하는 나무꾼이다. 그런데 어느 날 누가 나타나서 나무를 자르는 새로운 패러다임인 전기톱을 알리고 다닌다. 이 사람이 무척 설득력이 있어서 당신은 사용하는 방법도 모르면서 전기톱을 사게 된다. 당신은 여태껏 했던 방식대로 시동을 걸지도 않고 전기톱으로 나무를 마구 두들겨댄다. 곧 당신은 이 새로운 전기톱은 일시적인 유행일 뿐이라고 단정하고 다시 도끼를 쓰기 시작한다. 그때 누군가 나타나서 전기톱의 시동 거는 법을 가르쳐 준다. — “함수형 사고” 에서

**함수형 프로그래밍의 컨셉**
1. 변경 가능한 상태를 불변상태(Immutab)로 만들어 SideEffect를 없애자.
2. 모든 것은 객체이다.
3. 코드를 간결하게 하고 가독성을 높여 구현할 로직에 집중 시키자.
4. 동시성 작업을 보다 쉽게 안전하게 구현 하자.

### 프로그래밍에 대한 정의 (함수형 프로그래밍을 살짝 맛본 브랜든의 소심한 개인의견)
- 프로그래밍 이란 어떤 프로세스에 대한 소프트웨어적 표현 방식으로, 진행하는 업무 혹은 프로세스를 프로그래밍 언어의 관점에서 표현한것이라고 생각함. 
- 스프링 같은 경우 POJO 라는 사상을 프레임워크로 구현하여, 업무 혹은 프로세스적인 부분을 가독성있게 개발하여 비지니스 로직에 대한 분석을 좀 더 분명하게 가독성있게 하기위한 방법으로 시작하였다. 
- 어느정도 프로그래밍을 한 사람이라면 분석하기 편한게 좋은 프로그램이며, SOLID 방식으로 코드하는것도 이러한 성능이 좋고 가독성 있는 프로그래밍을 하는데 그 목적이 있다. 
- 함수형 프로그래밍도 위 사상과 다르지 않다. 기존 POJO 기반의 사항은 클래스에 대한 구조를 담고 있다면, 함수형 프로그래밍은 함수 즉 메소드를 어떻게 아이솔레이션해서 순수함수를 이용하여 외부의 변수에 대한 접근을 줄이고 가독성 있는 코드를 만드는데 그 목적이 있다고 볼 수 있다. 
- 누구나 그렇듯이 프로그래밍에 대한 철학이 있으며 기준이 있다. 조심스럽게 프로그래밍에 대한 의견을 써보았습니다~~ :) 

### 함수형 프로그래밍의 목적 (순수함수) 
-  함수형 프로그램의 목적은 함수를 사용할때 순수함수로 이용하자는게 가장 큰 목적~!! 
- 외부 변수 혹은 클래스 상태 변경으로 인한 함수의 동작에 영향이 없게 하는게 목적~! 
```
package com.brandon.funcprgm

fun pureAdd (x: Int, y:Int ) : Int {
    return x + y
}

val outer = 3

fun noPureAdd (x: Int, y:Int ) : Int {
    return x + y + outer // fun 은 return 으로~
}

fun main(){
    println("Pure Function : ${pureAdd(1,2)}")
    println("None Pure Function :  ${noPureAdd(1,2)}")
}
```
https://github.com/CodingBakery/KotlinStudy/blob/main/playground/src/main/kotlin/com/brandon/funcprgm/PureFunc.kt 
위 코드를 보면 f1은 순수함수, f2는 state라는 변수로 영향을 받는 None-순수함수. 


### 함수형 프로그래밍의 사용방법 (First-class citizen) 
- 함수형 프로그램으로 프로그래밍 하려면 이런 순수함수를 주입해야 해야하는데.. 그럼 기존 함수라는 넘이 메소드가 아닌 다른것으로 변신할수 있어야 한다. 그것이 바로 바로 아래칸에~~~~ 
- 함수는 변수, 파라메터, 리턴 값이 되어야 한다. 이것이 바로 일급객체, 일급함수(X) First-Class citizen ~!! 
- 위와 같이 되어야 다른 메소드에도 파라메터로 미리 만들어 놓을수도 있고(변수 (1)), 파라메터도 사용이 가능하하며(파라메터, 람다 (2)), 응답값으로도 (리턴 (3)) 도 쓰일수 있다. 

- (1) 함수를 변수에 반영 
```
package com.brandon.funcprgm

fun main() {
    val multi_newLine: (Int, Int) -> Int = {x: Int, y: Int ->
        println("x * y")
        x * y}
    // 람다함수에서 NewLine (Enter) 값을 기준으로 맨 아래가 return

    val multi1 : (Int, Int) -> Int = {x: Int, y: Int -> x * y}
    val multi1_1 : (Int, Int) -> Int = {x , y -> x * y}
    val multi2 = {x: Int, y: Int -> x * y}

    // val multi2err = {x, y -> x * y} // ERROR
    // 타입은 앞쪽 : 로 선언하든, 뒤쪽에 선언하든 해야함!

    println("${multi_newLine(3,4)}")

    val greet = {println("hello")} // 추론가능
    val square = {x: Int -> x*x} // square 의 자료형을 생략하려면 x의 자료형을 명시해야함.

    val nestedLamda = {{ println("nested")}} // 추론 가능.
    val nestedLamda2: () -> () -> Unit = {{println("nested")}} // 추론 가능.
}
```
- “:” 은 변수의 타입을 정의, 즉 함수의 형식을 정의하고 “=” 은 해당 변수에 행위or값을 정의합니다. 
- 위와 같은 관점이면 이해하기 조금은 편합니다~~ 
- 변수는 아래와 같이 정의는 가능한데... 2, 3 은... 다음스테이지 고차함수가 필요합니다~! 
[KotlinStudy/ValTest.kt at main · CodingBakery/KotlinStudy (github.com)](https://github.com/CodingBakery/KotlinStudy/blob/main/playground/src/main/kotlin/com/brandon/funcprgm/ValTest.kt) 

- (2), (3) 함수를 파라메터로 사용 (고차함수) 
```
package com.brandon.funcprgm

import java.util.concurrent.locks.ReentrantLock

fun main(){

    val multi1 : (Int, Int) -> Int = {x: Int, y: Int -> x * y}
    val multi1_1 : (Int, Int) -> Int = {x , y -> x * y}
    val multi2 = {x: Int, y: Int -> x * y}

    println(simpleHigherOrderFunction({ x, y -> x + y }, 10, 20)) // result: 30

    println("multi1 : ${funcParam( 10, 20, multi1)}") // 람다 함수 주입 시에는 그냥
    println("multi1_1 : ${funcParam( 10, 20, multi1_1)}") // 람다 함수 주입 시에는 그냥
    println("multi2 : ${funcParam( 10, 20, multi2)}") // 람다 함수 주입 시에는 그냥

    println("::minusFunc : ${funcParam( 10, 20, ::minusFunc)}") // fun 주입시에는 :: FunctionReference ~
}

fun minusFunc(a: Int, b: Int) = a-b

fun simpleHigherOrderFunction(sum: (Int, Int) -> Int, a: Int, b: Int): Int = sum(a, b)

fun funcParam(a: Int, b: Int, c:(Int, Int) -> Int) : Int {
    return c(a,b)
}
```
- 위쪽 변수 내용을 이용한 함수에 함수 주입하기~ 
- L10 은 함수를 변수 처럼 파라메터 사용~, L16 은 함수를 FunctionReference (:: 로 표기) 하여 주입 
[KotlinStudy/HighOrder.kt at main · CodingBakery/KotlinStudy (github.com)](https://github.com/CodingBakery/KotlinStudy/blob/main/playground/src/main/kotlin/com/brandon/funcprgm/HighOrder.kt) 

[KotlinStudy/LamdaFunc.kt at main · CodingBakery/KotlinStudy (github.com)](https://github.com/CodingBakery/KotlinStudy/blob/main/playground/src/main/kotlin/com/brandon/funcprgm/LamdaFunc.kt) 
```
package com.brandon.funcprgm

fun main(){
    val result1 = callByValue1(lambda())
    println(result1)
    val result2 = callByValue2(otherlambda)
    println(result2)
}

fun callByValue1(b: Boolean) : Boolean{
    println("CallByValue1 Func")
    return b
}

val lambda: () -> Boolean = {
    println("Lamda1 Func")
    true
}

fun callByValue2(b: ()-> Boolean) : Boolean{
    println("CallByValue2 Func")
    return b()
}

val otherlambda: () -> Boolean = {
    println("otherlambda2 Func")
    true
}
```
- CallByValue 의 입력 파라메터가 값, 혹은 함수 (L10, L20) 에 따라 입력하는 값(L4, L6)이 달라진다. 


### 확장 함수 예제 
```
package com.brandon.funcprgm
fun main(){

    val source = "Hello Kotlin"
    val target = "Target"
    println(source.getLongString(target))

}
fun String.getLongString(target: String): String =
    if(this.length > target.length) this else target
```
- 기존에 있는 클래스에 함수를 추가해서 사용할 수 있다. 
[KotlinStudy/ExtensionFunc.kt at main · CodingBakery/KotlinStudy (github.com)](https://github.com/CodingBakery/KotlinStudy/blob/main/playground/src/main/kotlin/com/brandon/funcprgm/ExtensionFunc.kt)

**Comment by DevBono** [comment]
**함수 내부의 함수를 바깥 함수에서 접근 (ex. JS의 클로저 함수)**
- 자바는 final인 것만 사용 가능하게 컴파일을 막아두는데
  - 아래와 같은 이유로.. 람다가 수행되는 stack 에서 이전 상위 메소드의 stack 의 primitive 값을 변경 적용할 수 없기 때문
  - https://cobbybb.tistory.com/19
- 코틀린은 수정도 가능? 왜 그럴까요?
  - 아래와 같이 Ref<T>(var value: T) 라는 final 클래스로 만들고 실제 값은 Ref 객체의 필드를 변경하기 때문에 가능 
  - https://lovia98.github.io/blog/kotlin-lamda.html
