### ISSUE TITLE
[6/16(목)]코틀린은 자바와 뭐가 다를까

### ISSUE THREAD

**Issue by onisley** [CodingBakery/KotlinStudy#4]
### 개요 
Java 개발자인 스터디 참석자들이 코틀린이라는 언어를 사용함에 있어 어떤 부분이 다르고 주의가 필요한지 비교 분석을 목적으로 함

코틀린도 자바와 동일하게 서버/앱 개발에 대표적으로 사용되며, JVM에서 동작한다는 점은 동일하다. 
코틀린은 Java 와의 상호 운영성을 중시하므로 거의 100% 상호 호환이 가능하다.  
- 상호 호환을 통해 자바를 완전히 대체할 수 있는 언어가 되는 것이 주목적? 

Java 보다는 JS의 문법과 많이 유사하다는 것을 느낄 수 있다. 

#### 전체적으로 받은 느낌 
- Java 를 이용하여 개발하면서 겪은 불편한 점들을 개선  
- 코드량을 감소 
- Java에서 이루지 못한 것들을 반영? 
- Class 를 정의하지 않고 함수 선언 가능  
- 기본적으로 클래스는 상속되지 않게 하기 등

**Comment by DevBono** [comment]
별도의 마크 다운 파일로 발표 내용을 기재해두었습니다
- [발표 내용 보러 가기](https://github.com/CodingBakery/KotlinStudy/blob/main/content/%EC%BD%94%ED%8B%80%EB%A6%B0%EC%9D%80_%EC%9E%90%EB%B0%94%EC%99%80_%EB%AD%90%EA%B0%80_%EB%8B%A4%EB%A5%BC%EA%B9%8C.md)
