### ISSUE TITLE
[6/27(월)] 코틀린의 확장 함수

### ISSUE THREAD

**Issue by onisley** [CodingBakery/KotlinStudy#8]
### 개요
- 확장 함수의 개요와 활용
- 그리고 궁금증들
  - 그렇게 정의된 확장 함수를 다른 .kt 파일에서도 활용할 수 있는지?

**Comment by onisley** [comment]
발표자료: <a href="https://github.com/CodingBakery/KotlinStudy/blob/main/content/%ED%99%95%EC%9E%A5%ED%95%A8%EC%88%98.md">확장함수.md</a>

**Comment by DevBono** [comment]
확장 프로퍼티의 setter 에 대한 활용을 어떻게 할지 감이 안 왔었는데 이런 예제도 있었네요 ~ 
```kotlin
var StringBuilder.lastChar: Char
    get() = get(length - 1)
    set(value: Char) {
        this.setCharAt(length - 1, value)
    }
```
