### ISSUE TITLE
[6/24(금)] 코틀린에서의 Composite 구성

### ISSUE THREAD

**Issue by onisley** [CodingBakery/KotlinStudy#9]
### 개요
- 주제를 간략하게 설명해주세요.

**Comment by eager20** [comment]
클래스와 클래스의 관계
========

### 1. 연관 (Association)
- 의사는 여러명의 환자를 가지고 있다.
- 환자는 여러명의 의사를 가지고 있다.
- 하나의 객체가 다른 객체의 구성요소가 된다.
- 둘다 독립적인 생명주기를 가지고 있다.
```
class Patient(val name: String) {
    fun doctorList(d: Doctor) {  // 인자로 참조
        println("Patient: $name, Doctor: ${d.name}")
    }
}

class Doctor(val name: String) {
    fun patientList(p: Patient) { // 인자로 참조
        println("Doctor: $name, Patient: ${p.name}")
    }
}

fun main() {
    val doc1 = Doctor("KimSabu")
    val patient1 = Patient("Kildong")
    doc1.patientList(patient1)
    patient1.doctorList(doc1)
}
```
<img width="526" alt="image" src="https://user-images.githubusercontent.com/24687822/174485947-3ca08edd-ae69-4b69-bc9e-ea1eb653c796.png">


### 2. 의존 (Dependency)
- 의사가 생성될때는 1명의 환자가 있어야 한다.
- 의사는 환자에게 의존적인다.
- 환자가 있어야 의사가 존재할수 있다. 즉 의사는 환자에 의존적이다.
```
class Patient(val name: String, var id: Int) {
    fun doctorList(d: Doctor) {
        println("Patient: $name, Doctor: ${d.name}")
    }
}

class Doctor(val name: String, val p: Patient) {

    val customerId: Int = p.id
    fun patientList() {
        println("Doctor: $name, Patient: ${p.name}")
        println("Patient Id: $customerId")
    }
}

fun main() {
    val patient1 = Patient("Kildong", 1234)
    val doc1 = Doctor("KimSabu", patient1)
    doc1.patientList()
}
```
<img width="518" alt="image" src="https://user-images.githubusercontent.com/24687822/174486097-34db42d9-543d-44fa-8f78-7b388197825d.png">


### 3. 집합 (Aggregation)
- 연못(Pond)에는 여려마리의 오리가 있다.
- 연못, 오리는 생명주기(객체를 생성할때...)에 영향을 주지 않는다.
- 오리는 연못안에 있으면서 외부에 이름을 알릴 수 있습니다. (오픈되어 있음.)
- 오리 new는 연못 밖 연못과 같으 레벨에서 함.
-  여럿의 오리를 위한 List 매개변수
```
class Pond(_name: String, _members: MutableList<Duck>) {
    val name: String = _name
    val members: MutableList<Duck> = _members
    constructor(_name: String): this(_name, mutableListOf<Duck>())
}

class Duck(val name: String)

fun main() {

    // 두 개체는 서로 생명주기에 영향을 주지 않는다.
    val pond = Pond("myFavorite")
    val duck1 = Duck("Duck1")
    val duck2 = Duck("Duck2")

    // 연못에 오리를 추가 - 연못에 오리가 집합한다
    pond.members.add(duck1)
    pond.members.add(duck2)

    // 연못에 있는 오리들
    for (duck in pond.members) {
        println(duck.name)
    }
}
```
<img width="519" alt="image" src="https://user-images.githubusercontent.com/24687822/174486010-d39d7e1a-9d01-430b-a9dc-e5c267548c11.png">


### 4. 구성 (Composition)
- 자동차 안에는 엔진이라는 객체가 존재 하며, 엔진이 없으면 차는 구성될 수가 없다.
- 엔진객체는 자동차 객체가 없으질때 같이 소멸됩니다. (생명주기 공동체~)
- 엔진은 자동차 외부에서 정보를 알수 없으며, 단지 행위만을 오픈함.
- 엔진 new 를 자동차 안에서 함~!!

```
class Car(val name: String, val power: String) {
    private var engine = Engine(power) // Engine클래스 객체는 Car에 의존적이다
    fun startEngine() = engine.start()
    fun stopEngine() = engine.stop()
}

class Engine(power: String) {
    fun start() = println("Engine has been started.")
    fun stop() = println("Engine has been stopped.")
}

fun main() {
    val car = Car("tico", "100hp")
    car.startEngine() // 요런게 위임(delegation) 이라고 볼수 있음~
    car.stopEngine()
}
```
![image](https://user-images.githubusercontent.com/24687822/174486558-3a9dc2f2-d8bd-488d-8e58-451f90615a4c.png)

ex) 
### 구성 (Composition) 에서의 위임(delegation)이란?
- 위임이란 '어떤 메서드의 처리를 다른 인스턴스의 메서드에 맡긴다'는 의미.
- 즉, 클라이언트 코드에서 구성(composite)하고 있는 참조 객체를 통해 메서드를 호출하는 것(delegation)을 말함.
- 참조 사이트 : https://skkcha.tistory.com/32

**Comment by eager20** [comment]
### 상속(Interitance, is-a) VS 구성 (Composition, has-a) 에서의 위임(delegation)

: 그렇다  **상속(is-a)**  으로 프로그램을 구현하는것 보다는, 
마더?클래스 내부에 내부?클래스를 생성해서 **구성(Composition, has-a)** 하고 
내부?된 클래스의  **기능을 위임(delegation)** 받아 사용하라는 이야기이다.

### 참조사이트 
https://soft.plusblog.co.kr/89
https://zangzangs.tistory.com/44
